import { existsSync, readdirSync, readFileSync } from "node:fs";
import { join } from "node:path";

const ident = (s: string) => s.replace(/[^a-z0-9]+/gi, "_");

export function generateIndex(root: string): string {
  const componentsDir = join(root, "components");
  const presetsDir = join(root, "presets");
  const imports: string[] = [];
  const entries: string[] = [];
  const skipped: string[] = [];

  const ids = existsSync(componentsDir)
    ? readdirSync(componentsDir, { withFileTypes: true })
        .filter((d) => d.isDirectory())
        .map((d) => d.name)
        .sort()
    : [];
  for (const id of ids) {
    const dir = join(componentsDir, id);
    if (!existsSync(join(dir, "render.ts"))) {
      skipped.push(id);
      continue;
    }
    const v = ident(id);
    const renderSrc = readFileSync(join(dir, "render.ts"), "utf8");
    const hasCss = /export const css\b/.test(renderSrc);
    const hasChecks = /export const checks\b/.test(renderSrc);
    const hasOrientation = /export const orientation\b/.test(renderSrc);
    imports.push(`import meta_${v} from "../../components/${id}/component.json";`);
    imports.push(
      `import { render as render_${v}${hasCss ? `, css as css_${v}` : ""}${hasChecks ? `, checks as checks_${v}` : ""}${hasOrientation ? `, orientation as orientation_${v}` : ""} } from "../../components/${id}/render";`,
    );
    const exDir = join(dir, "examples");
    const files = existsSync(exDir)
      ? readdirSync(exDir)
          .filter((f) => f.endsWith(".json"))
          .sort()
      : [];
    const examples = files.map((file) => {
      const name = file.replace(/\.json$/, "");
      const ev = `ex_${v}_${ident(name)}`;
      imports.push(`import ${ev} from "../../components/${id}/examples/${file}";`);
      return `${JSON.stringify(name)}: ${ev}`;
    });
    entries.push(
      `  { meta: meta_${v} as unknown as ComponentModule["meta"], render: render_${v}, ${hasCss ? `css: css_${v}, ` : ""}${hasChecks ? `checks: checks_${v}, ` : ""}${hasOrientation ? `orientation: orientation_${v}, ` : ""}examples: { ${examples.join(", ")} } as ComponentModule["examples"] },`,
    );
  }

  const presetFiles = existsSync(presetsDir)
    ? readdirSync(presetsDir)
        .filter((f) => f.endsWith(".json"))
        .sort()
    : [];
  const presets = presetFiles.map((file) => {
    const pv = `preset_${ident(file.replace(/\.json$/, ""))}`;
    imports.push(`import ${pv} from "../../presets/${file}";`);
    return `${pv} as unknown as PresetMeta`;
  });

  // Collections: a folder each, holding collection.json and, optionally, its own presets.
  const collectionsDir = join(root, "collections");
  const collectionIds = existsSync(collectionsDir)
    ? readdirSync(collectionsDir, { withFileTypes: true })
        .filter((d) => d.isDirectory() && existsSync(join(collectionsDir, d.name, "collection.json")))
        .map((d) => d.name)
        .sort()
    : [];
  const collections = collectionIds.map((id) => {
    const v = ident(id);
    imports.push(`import collection_${v} from "../../collections/${id}/collection.json";`);
    const ownDir = join(collectionsDir, id, "presets");
    const own = existsSync(ownDir)
      ? readdirSync(ownDir)
          .filter((f) => f.endsWith(".json"))
          .sort()
      : [];
    const presetVars = own.map((file) => {
      const pv = `collection_${v}_preset_${ident(file.replace(/\.json$/, ""))}`;
      imports.push(`import ${pv} from "../../collections/${id}/presets/${file}";`);
      return `${pv} as unknown as PresetMeta`;
    });
    return `  { dir: ${JSON.stringify(id)}, meta: collection_${v} as unknown as CollectionModule["meta"], presets: [${presetVars.join(", ")}] },`;
  });

  return [
    "// Generated by scripts/gen-components.ts. Do not edit; run `pnpm gen`.",
    'import type { CollectionModule, ComponentModule, PresetMeta } from "../engine/types";',
    ...imports,
    "",
    "export const components: ComponentModule[] = [",
    ...entries,
    "];",
    "",
    `export const presets: PresetMeta[] = [${presets.join(", ")}];`,
    "",
    "export const collections: CollectionModule[] = [",
    ...collections,
    "];",
    "",
    `export const skipped: string[] = ${JSON.stringify(skipped)};`,
    "",
  ].join("\n");
}
